services:
  backend:
    environment:
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      CONNECTION_URL: "postgresql://postgres:password@db:5432/smart_hospital_system"
      JWT_SECRET_KEY: "JWT_SECRET_KEY_BACKEND_GO_HOSPITAL_SYSTEM"
    build: ./backend
    ports:
      - "4567:4567"
    volumes:
      - ./backend:/backend
    command: air

  frontend:
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      REACT_APP_AWS_PROJECT_REGION: "ap-southeast-2"
      REACT_APP_AWS_COGNITO_REGION: "ap-southeast-2"
      REACT_APP_AWS_USER_POOLS_ID: "ap-southeast-2_LHPms3R3t"
      REACT_APP_CLIENT_ID: "3j5rj5cggdh8tfkq2l4hhdimku"
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - ./tsconfig.json:/app/tsconfig.json

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local