#!/usr/bin/bash

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="db-create"
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"

# Explicitly set host and port
DB_HOST="localhost"
DB_PORT="5432"
DB_USER="postgres"
DB_NAME="smart_hospital_system"

# Update connection URL
NO_DB_CONNECTION_URL="postgresql://$DB_USER:password@$DB_HOST:$DB_PORT"

# Create database
psql "$NO_DB_CONNECTION_URL" -c "CREATE DATABASE $DB_NAME"