#! /usr/bin/bash
-e # stop if it fails at any point

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="db-setup"
printf "${CYAN}==== ${LABEL}${NO_COLOR}\n"

utils_path="$(realpath .)/utils"

source "$utils_path/db-drop"
source "$utils_path/db-create"
source "$utils_path/db-schema-load"
source "$utils_path/db-seed"