#! /usr/bin/bash

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="db-schema-load"
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"

schema_path="$(realpath .)/db/schema.sql"
echo $schema_path

if [ "$1" == "prod" ]; then
    echo "using production"
    CON_URL=$PROD_CONNECTION_URL
else
    # CON_URL=$CONNECTION_URL
    CON_URL=postgresql://postgres:password@localhost:5432/smart_hospital_system
fi

psql $CON_URL smart_hospital_system < $schema_path